### ISSUE TITLE
Document requirements

### ISSUE THREAD

**Issue by lkngtn** [1Hive/dandelion-org#2]

**Comment by yeqbfgxjiq** [comment]
Items that would go into shipping the Dandelion Kit as a cohesive package:

Dandelion Org Template (stuff for people who want to build a DAO for their community/project with all the apps together)
- an example demo dao on the web that people can look at 
- a web portal that allows people to set up their own dao (like https://rinkeby.aragon.org/)
- a dev dependencies sections that helps people go from a blank slate to whatever they need to build the Dandelion Org
- a cli template that allows devs to spin up and configure a DAO quickly 
- docs describing best practices and recommended configurations for the template, esp regarding security related risks of misconfiguring permissions
- a "user dependencies" page that explains/links to things users need to interact the DAO (metamask, etc....)

For Each Aragon App...
- user guides
- example video/gif showing what should/could happen when the app is working
- code is organized and commented so that developers know what is what, what they do and why, and any gotchas/snafus to look out for
- basic docs explaining the various functions of each app, what they do, and what they're intended to connect to (to help people integrating them into their DAOs)
- "quickstart" developer integration guide to just add the app to an existing DAO with sane defaults

All of this can then be presented on a website (docusaurus) in an intuitive, organized, and easy to access way :)

Does this more or less sound good and/or is there stuff I'm missing we should add?

**Comment by 0xGabi** [comment]
Sound great. I think it might make sense to include as part of the deliverables of the dandelion kit to have a deployment history as discussed in last sprint call.

**Comment by yeqbfgxjiq** [comment]
Do you mean something like this?
- https://github.com/aragon/aragon/deployments

**Comment by 0xGabi** [comment]
Yes exactly. Maybe we can even improve how that information is both gather and generated when publishing an app. Other possible suggestion I been thinking about is having a `deployment_changelog` file 🤔

**Comment by 0xGabi** [comment]
Autark is currently doing it [like this](https://github.com/AutarkLabs/planning-suite/tree/dev/shared/deployments).
